# Generated by Django 5.0.4 on 2026-01-02 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+359[0-9]{9}$', "Phone number must start with '+359' followed by 9 digits")]),
        ),
    ]
