# Generated by Django 5.2.10 on 2026-01-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='Image_url',
            new_name='image_url',
        ),
    ]
