# Generated by Django 5.0.4 on 2025-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Dell', 'Dell'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus')], default='Asus', max_length=20)),
                ('processor', models.CharField(default='Unknown Processor', max_length=100)),
                ('memory', models.PositiveIntegerField(default=8, help_text='Memory in GB')),
                ('storage', models.PositiveIntegerField(default=256, help_text='Storage in GB')),
                ('operation_system', models.CharField(choices=[('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Linux', 'Linux'), ('Chrome OS', 'Chrome OS')], default='Windows', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
            ],
        ),
    ]
