# Generated by Django 5.0.4 on 2025-12-22 20:17

from django.db import migrations

from main_app.models import Person


def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    people = PersonModel.objects.all()
    for p in people:
        if p.age<=12:
            p.age_group = 'Child'
        elif p.age<18:
            p.age_group = 'Teen'
        else:
            p.age_group = 'Adult'
        p.save()

def reverse_set_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    people = PersonModel.objects.all()
    for p in people:
        p.age_group = PersonModel._meta.get_field('age_group').default
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_set_age_group),
    ]
