# Generated by Django 5.0.4 on 2025-12-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_migrate_person_age_group'),
        ('main_app', '0013_item'),
    ]

    operations = [
    ]
