# Generated by Django 5.0.4 on 2025-12-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_0011_migrate_person_age_group_0013_item'),
        ('main_app', '0015_migrate_item_rarety'),
    ]

    operations = [
    ]
