# Generated by Django 5.0.4 on 2025-12-22 21:24

from django.db import migrations

from main_app.models import Smartphone


def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    for phone in SmartphoneModel.objects.all():
        phone.new_price = len(phone.brand) * 120
        phone.save()


def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    for phone in SmartphoneModel.objects.all():
        if phone.price <= 750:
            phone.category = 'Cheap'
        else:
            phone.category = 'Expensive'
        phone.save()

def set_fields(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reverse_fields(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    category_default = SmartphoneModel._meta.get_field('category').default
    price_default= SmartphoneModel._meta.get_field('price').default
    for phone in SmartphoneModel.objects.all():
        phone.new_price = price_default
        phone.category = category_default
        phone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_fields, reverse_fields),
    ]
