# Generated by Django 5.0.4 on 2025-12-23 09:00
from datetime import timedelta

from django.db import migrations

from choices import OrderStatusChoices


def set_fields(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    for order in Order.objects.all():
        if order.status == OrderStatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == OrderStatusChoices.COMPLETED:
            order.warranty = '24 months'
            order.save()
        elif order.status == OrderStatusChoices.CANCELLED:
            order.delete()

def reverse_func(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_order'),
    ]

    operations = [
        migrations.RunPython(set_fields, reverse_func),
    ]
